{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-santoku
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/santoku_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/santoku/santoku_{{ version }}.tar.gz
  sha256: 9e15d8ef40c37b9b1dd30dac8d82ee3988f585892a1ca0fe1f774492d600f422

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-assertthat
    - r-glue
    - r-lifecycle
    - r-rlang
    - r-vctrs
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-assertthat
    - r-glue
    - r-lifecycle
    - r-rlang
    - r-vctrs

test:
  commands:
    - $R -e "library('santoku')"           # [not win]
    - "\"%R%\" -e \"library('santoku')\""  # [win]

about:
  home: https://github.com/hughjonesd/santoku, https://hughjonesd.github.io/santoku/
  license: MIT
  summary: A tool for cutting data into intervals. Allows singleton intervals. Always includes the whole range of data by default. Flexible labelling. Convenience functions for cutting by quantiles etc. Handles dates, times, units and other vectors.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
